### ISSUE TITLE
release 0.2.0

### ISSUE THREAD

**Issue by theskumar** [pydelhi/pydelhi.github.io#3]
Goal: Extend and polishup the existing website.

----

- [x] create/add favicon or other kind of meta images
- [x] add fb/schema.org/google meta info (#11, #12)
- [x] add sub-action-items to social links
- [x] Add mailing list guidelines (#6)
- [x] add next event section on homepage (#9)

__Changes__

- [x] make links mobile friendly. 

Feature Requests goes as comments below and should be added here upon consensus.
